package com.samsung.incentive;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String schemeName;
	private java.util.Date schemeStartDate;
	private java.util.Date schemeEndDate;
	private java.lang.String productType;
	private java.lang.String incentiveNature;

	public Response() {
	}

	public java.lang.String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(java.lang.String schemeName) {
		this.schemeName = schemeName;
	}

	public java.util.Date getSchemeStartDate() {
		return this.schemeStartDate;
	}

	public void setSchemeStartDate(java.util.Date schemeStartDate) {
		this.schemeStartDate = schemeStartDate;
	}

	public java.util.Date getSchemeEndDate() {
		return this.schemeEndDate;
	}

	public void setSchemeEndDate(java.util.Date schemeEndDate) {
		this.schemeEndDate = schemeEndDate;
	}

	public java.lang.String getProductType() {
		return this.productType;
	}

	public void setProductType(java.lang.String productType) {
		this.productType = productType;
	}

	public java.lang.String getIncentiveNature() {
		return this.incentiveNature;
	}

	public void setIncentiveNature(java.lang.String incentiveNature) {
		this.incentiveNature = incentiveNature;
	}

	public Response(java.lang.String schemeName,
			java.util.Date schemeStartDate, java.util.Date schemeEndDate,
			java.lang.String productType, java.lang.String incentiveNature) {
		this.schemeName = schemeName;
		this.schemeStartDate = schemeStartDate;
		this.schemeEndDate = schemeEndDate;
		this.productType = productType;
		this.incentiveNature = incentiveNature;
	}

}